// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCJ6OwEY_mgBiAr5gyyGtfW33atO76HtI',
    appId: '1:942306724641:web:e03a98ef360f23e1e98c60',
    messagingSenderId: '942306724641',
    projectId: 'mansa-70713',
    authDomain: 'mansa-70713.firebaseapp.com',
    storageBucket: 'mansa-70713.appspot.com',
    measurementId: 'G-X0EGKY80BF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA20RDThIY4RKwJ5_n3i87Zv22W0pozotY',
    appId: '1:942306724641:android:3fdaee1903d9ba9de98c60',
    messagingSenderId: '942306724641',
    projectId: 'mansa-70713',
    storageBucket: 'mansa-70713.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRbUJ39bm8rWNv1QwnHvm43P1j4NQtb5A',
    appId: '1:942306724641:ios:7d4db1d8809ac43ae98c60',
    messagingSenderId: '942306724641',
    projectId: 'mansa-70713',
    storageBucket: 'mansa-70713.appspot.com',
    iosBundleId: 'com.trustholding.mansa.mansa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRbUJ39bm8rWNv1QwnHvm43P1j4NQtb5A',
    appId: '1:942306724641:ios:e3f37175ffee1e89e98c60',
    messagingSenderId: '942306724641',
    projectId: 'mansa-70713',
    storageBucket: 'mansa-70713.appspot.com',
    iosBundleId: 'com.trustholding.mansa.mansa.RunnerTests',
  );
}
