// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8hJAIiK5DUd0BGGdTzH4-3C_70iilbHI',
    appId: '1:125620699387:web:f97943a3107b17a7d0705e',
    messagingSenderId: '125620699387',
    projectId: 'mansa-e4477',
    authDomain: 'mansa-e4477.firebaseapp.com',
    storageBucket: 'mansa-e4477.appspot.com',
    measurementId: 'G-BJE6DT4NLF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF14rDE7N93jkN3tYrFjMGAM12iaVwZHs',
    appId: '1:125620699387:android:cc527d32d5d250bdd0705e',
    messagingSenderId: '125620699387',
    projectId: 'mansa-e4477',
    storageBucket: 'mansa-e4477.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtdsShbpPe_KoU8fudojBJiLW_k-8NBUM',
    appId: '1:125620699387:ios:f353470d39003ecad0705e',
    messagingSenderId: '125620699387',
    projectId: 'mansa-e4477',
    storageBucket: 'mansa-e4477.appspot.com',
    iosBundleId: 'com.trustholding.mansa.mansa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtdsShbpPe_KoU8fudojBJiLW_k-8NBUM',
    appId: '1:125620699387:ios:10cdbc1aacb03e0ad0705e',
    messagingSenderId: '125620699387',
    projectId: 'mansa-e4477',
    storageBucket: 'mansa-e4477.appspot.com',
    iosBundleId: 'com.trustholding.mansa.mansa.RunnerTests',
  );
}
