// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIGAdiWDTBCOpvQCDll7c5U3S5_lkPKrQ',
    appId: '1:1075954674202:web:cc735f0aefbba84de47fa3',
    messagingSenderId: '1075954674202',
    projectId: 'mansa-b93d3',
    authDomain: 'mansa-b93d3.firebaseapp.com',
    storageBucket: 'mansa-b93d3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPQZmma5MS8LtFCSW1DiwLXfQs2yNCNZI',
    appId: '1:1075954674202:android:b2770011b6decaebe47fa3',
    messagingSenderId: '1075954674202',
    projectId: 'mansa-b93d3',
    storageBucket: 'mansa-b93d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0RK4VW30tIWdrl20Nf9MwgSZcy5c32Sc',
    appId: '1:1075954674202:ios:328f8079f9bf254de47fa3',
    messagingSenderId: '1075954674202',
    projectId: 'mansa-b93d3',
    storageBucket: 'mansa-b93d3.appspot.com',
    iosBundleId: 'com.trustholding.mansa.mansa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0RK4VW30tIWdrl20Nf9MwgSZcy5c32Sc',
    appId: '1:1075954674202:ios:0447225dca48de02e47fa3',
    messagingSenderId: '1075954674202',
    projectId: 'mansa-b93d3',
    storageBucket: 'mansa-b93d3.appspot.com',
    iosBundleId: 'com.trustholding.mansa.mansa.RunnerTests',
  );
}
